### PR TITLE
makes the Warsow version configurable

### PR DESCRIPTION
**Pull request by luisdavim**
Hi,

This change makes the version to download configurable via ENV variable.

Luis

### CODE REVIEW

**Comment by s7b4** [comment]
Thanks for the update, I will merge this, ut not the docker-compose.yml part.

The idea is to have your own parameter file named custom.cfg for example and set at ct start time. config/default.cfg is tracked et already copied into the image.

I will try to make a better example.

Stéphane

**Comment by luisdavim** [comment]
Hi,

Thanks. The idea of the change to the compose file was that this way it would work out of the box without any changes and if someone needs a custom config they can change it. 

But I understand your point. 

Luís

**Comment by s7b4** [comment]
I understand too...
I will just comment the line and update the readme.

Stéphane

**Comment by luisdavim** [comment]
Great. 

Thanks.

**Pull request merged**
